# FastAPI 앱을 실행할 수 있는 Python 이미지를 가져옵니다.
FROM python:3.9-slim

# 작업 디렉토리를 설정합니다.
WORKDIR /app

# 필요 라이브러리들을 설치합니다.
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# FastAPI 앱을 실행할 포트를 개방합니다.
EXPOSE 8000

# FastAPI 앱을 실행합니다.
CMD ["uvicorn", "chat:app", "--host", "0.0.0.0", "--port", "8000"]